-- CRIAR USUÁRIO E BANCO DE DADOS
CREATE USER replica WITH REPLICATION PASSWORD '12345';
CREATE DATABASE primary_db;

-- CONECTAR AO DB
\c primary_db

-- CRIAR TABELAS E GARANTIR PERMISSÕES
CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100)
);
GRANT SELECT ON TABLE usuarios TO replica;

-- CRIAR PUBLICATION PARA TODAS TABELAS
CREATE PUBLICATION my_publication FOR ALL TABLES;
